name: Mirror and run GitLab CI

on: [push]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build doc
      run: | 
        git submodule init
        git submodule update
        cd os
        make
        cargo doc --no-deps --verbose
        echo '<meta http-equiv=refresh content=0;url=index.html>' >> target/riscv64gc-unknown-none-elf/doc/os/index.html
    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./os/target/riscv64gc-unknown-none-elf/doc