name: Mirror and run GitLab CI

on: [push]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build doc
      run: | 
        cd os
        rustup target add riscv64gc-unknown-none-elf
        cargo install cargo-binutils --vers ~0.2
        rustup component add rust-src
        rustup component add llvm-tools-preview
        cargo doc --no-deps --verbose
        echo '<meta http-equiv=refresh content=0;url=rcore-tutorial/index.html>' > target/riscv64gc-unknown-none-elf/doc/index.html
    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./os/target/riscv64gc-unknown-none-elf/doc